apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: test-con
          image: 655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/wy-app:15
---
apiVersion: v1
kind: Service
metadata:
  name: test-svc
spec:
  type: ClusterIP
  selector:
    app: test
  ports:
  - port: 3000
    targetPort: 3000
