apiVersion: apps/v1
kind: Deployment
metadata:
  name: wy-node-dep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wy-node
  template:
    metadata:
      labels:
        app: wy-node
    spec:
      containers:
        - name: wy-node-con
          image: 655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/wy-node:9
---
apiVersion: v1
kind: Service
metadata:
  name: wy-node-svc
spec:
  type: ClusterIP
  selector:
    app: wy-node
  ports:
  - port: 3000
    targetPort: 3000
