apiVersion: apps/v1
kind: Deployment
metadata:
  name: wy-seatapp-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wy-seatapp
  template:
    metadata:
      labels:
        app: wy-seatapp
    spec:
      serviceAccountName: eks-secret-manager
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eks-secret-credentials" 
      containers:
        - name: wy-seatapp-con
          image: 655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/wy-seatapp:47
          resources:
            requests:
              cpu: 50m
            limits:
              cpu: 500m
          envFrom:
          - secretRef:
              name: eks-secret
          volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: wy-py-svc
spec:
  type: ClusterIP
  selector:
    app: wy-seatapp
  ports:
    - port: 5000
      targetPort: 5000
